### PR TITLE
Minor edits to documentation

### PR DESCRIPTION
**Pull request by pagrubel**
Made some minor edits to documentation as I was reading.

### CODE REVIEW

**Comment by pagrubel** [comment]
I will reopen this with a branch

**Comment by pagrubel** [comment]
Hopefully the pull request of pats_dev will satisfy this issue @trandles-lanl

**Comment by paulbry** [comment]
#38 Just linking these together, missed it earlier.

**Comment by paulbry** [comment]
Please keep open until documentation has been updated with information related to BeeFlow + Charliecloud integration

**Comment by paulbry** [comment]
#53 Close after the bug fix, I think it should be good after that point.

**Comment by pagrubel** [comment]
Have we done this? provide an example of using the launcher in a slurm job script. If not open another issue

**Comment by paulbry** [comment]
Missed that one.
Do we mean something along the lines:
```
# SBATCH ...
module load charliecloud python/2.7-anaconda-5.0.1
source activate bee_env
screen -S beeJobID -d -m bee_orc_ctl.py ...
sleep 15
bee_launcher.py -l demoBee
```
At this moment we have to run it via either a separate console or screen for this process to work. In order to support simply running the orchestrator (without these requirements) we would need to:
1. Account for passing a beefile to the orchestrator and initiate the task using the necessary methods from the launcher.
2. Determine a similar process for flow as well.
3. Realized in my thesis that I would need to account for stopping the orchestrator during the terminate step of a task. This too would need implemented.

Initial thoughts, though we can work around 1 and 2 with `screen` the fact orchestrator will keep running could be an issue. I have experimented invoking the `shutdown()` method (https://pythonhosted.org/Pyro4/api/core.html#Pyro4.core.Daemon.shutdown) and think this might be an option we could tie to a flag in the beefile?

**Comment by paulbry** [comment]
Closing this issue, I have moved the orchestrator termination to another issue

**Pull request closed without merging**
