### PR TITLE
Jieyang dev

### PR DESCRIPTION
**Pull request by cjy7117**
Merge BEE-OS functionality into master branch

### CODE REVIEW

**Comment by JieyangChen7** [comment]
I reviewed this PR. I think we can approve.

**Comment by JieyangChen7** [comment]
@trandles-lanl The two calls are working fine on my local testbed. I haven't been able to find alternatives better than the current calls.  The os module is still being used in some part of the code. I will verify it and remove some of them if necessary.

@pagrubel Can you check if os.getuid and os.getgid still work on LANL machines?

**Comment by pagrubel** [comment]
I'll try to look at it tomorrow

**Comment by pagrubel** [comment]
I ran my lammps example. I had to disable the charliecloud launcher, its not working in master and some changes for it leaked into master. Sorry git got me. I'll push that change to this branch.
@cjy7117 What examples should I run on darwin to make sure that all is well.

**Comment by pagrubel** [comment]
@trandles-lanl @cjy7117  I was able to run the example using bee-vm The flecsale example itself had some problems but I think we should go ahead and merge this. We need an issue for checking the examples or we can do that with Jieyang's pull request

**Pull request merged**
