### PR TITLE
Slurm command line worker

### PR DESCRIPTION
**Pull request by jtronge**
I think this should address issue #635. It renames the slurmrestd config section to `slurm` and adds a new `use_commands` option that gets set by beecfg.

I'd like to test this somehow, although it probably wouldn't be feasible to do in CI without adding too much time.

### CODE REVIEW

**Comment by pagrubel** [comment]
Is there a way to set up a test and run a github action before merge, even if it is manual?
Then we could change our procedures to make sure that is done before merging.

**Comment by jtronge** [comment]
Yeah I could edit the CI scripts one time and remove the WIP.

**Comment by pagrubel** [comment]
That may be okay for getting the PR merged but not practical for ensuring future merges don't fail

**Comment by pagrubel** [comment]
@jtronge Let's figure a way to test it manually on darwin and then we can set up some nightly tests

**Comment by pagrubel** [comment]
I tested this on darwin by removing the path to slurmrestd from $PATH and rerunning beecfg new, and it works fine. I still don't know how we would make this an automated test though.
@jtronge What do you think about making the "Not using slurmrestd" red or some color?

**Comment by pagrubel** [comment]
@jtronge for CI would it be too expensive to do the following to test using commands instead of slurmrestd: 
After the current integration test stop beeflow; change the value of use_commands to True in bee.conf and re run the tests?  It won't test the configuration but atleast if the commands change for some reason BEE won't break

**Comment by jtronge** [comment]
@pagrubel I think I found a way to make the slurm worker unit tests run with commands as well.

If you run it with `pytest beeflow/tests/test_slurm_worker.py -v`, it should show tests run with/without slurmrestd.

**Review by pagrubel — APPROVED** [review]

**Pull request merged**
