### PR TITLE
Fix slurmrestd version function

### PR DESCRIPTION
**Pull request by rstyd**
This PR fixes the slurmrestd inference function. It also adds a debug message that states what version it finds.

### CODE REVIEW

**Review by pagrubel — COMMENTED** [review]
@rstyd Should there be a fix for the configuration file?

**Comment by pagrubel** [comment]
Please remove api version from config and use whatever is installed.

**Comment by pagrubel** [comment]
I tried this out with and without slurmrestd and it seems to work well. I haven't reviewed the changes yet.

**Review by kchilleri — APPROVED** [review]
This also works for me + I can find the openapi_version in the beeflow logs.

**Pull request merged**
