### PR TITLE
Generate CWL

### PR DESCRIPTION
**Pull request by rstyd**
This PR adds code to generate a bee compatible CWL workflow using python.

### CODE REVIEW

**Comment by pagrubel** [comment]
@rstyd Do you have an example of a multi-step workflow?

**Comment by aquan9** [comment]
Looks like it's failing linting at the moment.

**Review by aquan9 — COMMENTED** [review]
One thing I noticed that's still missing is some documentation. The example is good. I'll give it a shot, but it would be good to also have a page in our documentation saying how to use it. Or maybe make an issue.

**Comment by rstyd** [comment]
I'll make an issue, and we can just use it internally for now.

**Comment by pagrubel** [comment]
I agree with Andres about documentation but am also fine with that being a separate PR. Having an issue for it will suffice.

**Review by pagrubel — APPROVED** [review]
We will need PR's for fixing the comd example and adding some documentation, however the generate code works for simple workflows and for cat-grep-tar with dependencies.

**Pull request merged**
