### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by pagrubel**
Minor errors to documentation fixed

### CODE REVIEW

**Comment by trandles-lanl** [comment]
We need to generate a dependency list for the BEE components.  This is especially important for anything being imported by python.

**Comment by paulbry** [comment]
I feel like this is a duplicate of #25, the discussions/work related to that issue directly address this enhancement.

**Comment by trandles-lanl** [comment]
Want to look at doing "pip install bee" and also getting bee into spack.

Assignee for wheel file (pip): 

Assignee for spackaging:

**Comment by paulbry** [comment]
Just wanted to clarify one of the things I was wrong about yesterday that I realized.
So, with BeeExperiment's `setup.py` (https://github.com/paulbry/BeeExperiment/blob/master/src/setup.py) you can see I have defined:
```python
    entry_points={
        'console_scripts': [
            'bee-launcher = bee_launcher.__main__:main',
            'bee-orchestrator = bee_orchestrator.__main__:main',
            'bee-monitor = bee_monitor.__main__:main'
        ]
    }
```

With `setuptools` it will automatically generate the necessary scripts under `/usr/bin` (default) for a privileged installation `pip3 install .`

The same thing will occur in `/home/paul/.local/bin` when we preform `pip3 install . --user`.

Just wanted to clarify this, hope it helps. You don't have to go with process I did but I think it will help identify easier deployment methods.

Source: https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation

**Comment by trandles-lanl** [comment]
Thanks for the info @paulbry 

I've created an account on test.pypi.org while I figure out this process.

**Comment by paulbry** [comment]
Honestly never knew that exists, that seems helpful.

**Comment by trandles-lanl** [comment]
Duplicate of #25

**Pull request merged**
