### PR TITLE
Ensure failed tasks cause dependent tasks to fail

### PR DESCRIPTION
**Pull request by jtronge**
This should address issue #688. When a task fails, all dependent tasks will get a state of `DEP_FAIL` and the workflow will fail without running anything else.

### CODE REVIEW

**Comment by pagrubel** [comment]
@jtronge I tried this out. It works well. Even though the workflow doesn't finish I think it should tar up the artifacts and archive them.

**Comment by jtronge** [comment]
@pagrubel Should the workflow state remain `Failed` when an unfinished workflow gets archived?

**Comment by rstyd** [comment]
How about ARCHIVED/Failed?

**Comment by jtronge** [comment]
I think `Archived/Failed` should be good. Failed workflows should be getting archived now, including the ones caused by build failures.

We seem to be having poetry problems on recent CI runs. Poetry's failing with`Package docutils (0.21.post1) not found.`.

**Comment by pagrubel** [comment]
Thanks @jtronge I like the Archive/Failed state and still have the archive for error analysis.

**Review by pagrubel — APPROVED** [review]

**Pull request merged**
