### PR TITLE
Need to remove src

### PR DESCRIPTION
**Pull request by pagrubel**
In order to publish we needed to remove src and change the pypoetry.toml file.
I'm not sure if we want to keep the /dist directory or add a .gitignore. 
We can discuss this on Monday

### CODE REVIEW

**Comment by pagrubel** [comment]
Added WIP need to fix path's for tests etc.

**Review by Boogie3D — CHANGES_REQUESTED** [review]
Usually `dist` isn't included in the repository for a Python project

**Comment by Boogie3D** [comment]
May also want to put `dist/` in `.gitignore`

**Comment by pagrubel** [comment]
I’m trying to figure out how the user can have access to the tar ball. They can get examples from there.

From: Steven Anaya ***@***.***>
Reply-To: lanl/BEE ***@***.***>
Date: Monday, August 22, 2022 at 9:59 AM
To: lanl/BEE ***@***.***>
Cc: "Grubel, Patricia A" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [lanl/BEE] Need to remove src (PR #530)


May also want to put dist/ in .gitignore

**Comment by Boogie3D** [comment]
> I’m trying to figure out how the user can have access to the tar ball. They can get examples from there.

I think they should just clone the repo if they want the examples.

**Comment by pagrubel** [comment]
I think there is a way with github release. I’ll try it out later this week and will put /dist in .gitignore for now

From: Steven Anaya ***@***.***>
Reply-To: lanl/BEE ***@***.***>
Date: Monday, August 22, 2022 at 10:50 AM
To: lanl/BEE ***@***.***>
Cc: "Grubel, Patricia A" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [lanl/BEE] Need to remove src (PR #530)


I’m trying to figure out how the user can have access to the tar ball. They can get examples from there.

I think they should just clone the repo if they want the examples.

**Comment by pagrubel** [comment]
@Boogie3D I think your requested changes have been done and this PR should be ready to merge.

**Review by Boogie3D — APPROVED** [review]

**Pull request merged**
