### PR TITLE
Allow Absolute/Relative Paths for Main CWL and YAML Files

### LINKED ISSUE #661: beeclient submit: interpret MAIN_CWL and YAML arguments as paths relative to ${PWD}
At the moment, `beeclient submit` seems to expect its MAIN_CWL and YAML arguments to be specified relative to WF_PATH. That's understandable, but it imposes a little extra friction in submitting a new workflow: I can't rely on my shell to auto-complete those filenames.

Could `beeclient submit` instead behave something like
```
Usage: beeclient submit [OPTIONS] WF_NAME MAIN_CWL YAML WORKDIR
```
i.e., where MAIN_CWL, YAML, and WORKDIR are all specified as either absolute pathnames or as pathnames relative to ${PWD}?

### PR DESCRIPTION
**Pull request by Boogie3D**
Allows for use of absolute/relative paths for `main_cwl` and `yaml` files in `beeclient submit` command, supporting autocomplete as requested in #661. This PR resolves #661.

### CODE REVIEW

**Comment by pagrubel** [comment]
I was not able to use relative paths on darwin Instead had to use absolute paths. I ran from $HOME I attempted entering BEE/ ... instead but it would not autocomplete. Here is my command:
``beeclient submit clarmbuild ~/BEE/BEE/examples/clamr-ffmpeg-build/ ~/BEE/BEE/examples/clamr-ffmpeg-build/clamr_wf.cwl ~/BEE/BEE/examples/clamr-ffmpeg-build/clamr_job.yml .``

**Review by pagrubel — COMMENTED** [review]
This works. Documentation needs to be added, that states that if the file requested for cwl and yml already exist in the path takes precedence. It would be helpful for provenance sake to capture the submit command or at least what yml file and main cwl file is used.

**Comment by pagrubel** [comment]
Looks good to me

**Review by aquan9 — APPROVED** [review]
This all looks good to me, It looks like you added the documentation that Pat wanted. I have nothing against merging this.

**Pull request merged**
