### PR TITLE
Archive Cancelled Workflows

### PR DESCRIPTION
**Pull request by Leahh02**
I was debating whether I should make this call to archive the workflow in wf_actions or wf_update. The calls to archive_workflow for other states are in wf_update, but I put it wf_actions to keep the full lifecycle of actions related to cancelling the workflow in one place.

### CODE REVIEW

**Review by pagrubel — COMMENTED** [review]
In general we have been marking states as Archived/{final_state} as they are archive. So I think we should stick to this format. I'll look to  see how this is used. I think it is also used when there is a reset.

**Review by pagrubel — CHANGES_REQUESTED** [review]
@Leahh02 This actually ended up with the state we need for the workflow.
```
clamr	be196f	Archived/Cancelled
```
when I ran it because when a workflow is archived it automatically adds the final state.
I'm not sure what happened to the state you add here.

Also, I'd like to see any dags that were run in the graphml files as well as the final dag in the archive. 

Sorry that this wasn't asked for in the issue. I ran some dags before cancelling the workflow. There are none in the archive. I'm thinking someone may have a complex workflow that they cancelled due to something like an upcoming DST and they want to quickly see what parts actually ran.

**Comment by Leahh02** [comment]
> @Leahh02 This actually ended up with the state we need for the workflow.
> 
> ```
> clamr	be196f	Archived/Cancelled
> ```
> 
> when I ran it because when a workflow is archived it automatically adds the final state. I'm not sure what happened to the state you add here.
> 
> Also, I'd like to see any dags that were run in the graphml files as well as the final dag in the archive.
> 
> Sorry that this wasn't asked for in the issue. I ran some dags before cancelling the workflow. There are none in the archive. I'm thinking someone may have a complex workflow that they cancelled due to something like an upcoming DST and they want to quickly see what parts actually ran.

I think I made the state "Cancelled and Archived" because I thought that would be reflected in the GDB. It's not, so I changed it back to the way it was for simplicity.

**Comment by Leahh02** [comment]
Right now the unit tests aren't testing archiving the workflow after it's been archived. I added the line `mocker.patch('beeflow.wf_manager.resources.wf_actions.archive_workflow', return_value=None)` to test_wf_manager to skip this. I was wondering if archiving should be in a different test.

**Comment by Leahh02** [comment]
all of the generated DAGs are now also being saved to the archive

**Comment by pagrubel** [comment]
Now the workflow is not actually being cancelled, instead it actually runs to completion:
beeflow query 0a
Archived/Cancelled
clamr--RUNNING
ffmpeg--WAITING

$ beeflow query 0a
Archived/Cancelled
clamr--COMPLETED
ffmpeg--PENDING

$ beeflow query 0a
Archived
clamr--COMPLETED
ffmpeg--COMPLETED

I didn't have time to look, but most likely the wf_manager is looking for the Cancelled state to stop it from running.

**Comment by pagrubel** [comment]
@Leahh02 This is not caused by your PR because it also occurs in the devlop branch.

**Comment by Leahh02** [comment]
> @Leahh02 This is not caused by your PR because it also occurs in the devlop branch.

That's so strange. I noticed it once while I was running a workflow, but I canceled it while tasks were completing, so I figured that's why it finished. That's definitely not the case in the example you gave.

I'll try to figure it out

**Review by pagrubel — APPROVED** [review]
This looks good. Cancelling is not working but is another issue #955 to be addressed. This addresses #894

**Pull request merged**
