### PR TITLE
529 version command

### LINKED ISSUE #529: beeflow --version command needed
Might be nice to support this version command

### PR DESCRIPTION
**Pull request by aquan9**
This resolves issue #529. I was able to get beeflow --version working (hopefully without breaking anything else).

### CODE REVIEW

**Comment by jtronge** [comment]
Ok, great. I tried this and it works. If we need to do anything more complicated then it might be worthwhile adding a toml parser, but I think this is good for now.

You'll need to fix the pylama lints and then I think it should be good to go (`pylama ${file}` will show what needs to be done).

**Comment by pagrubel** [comment]
I'm not sure this will work if someone installs beeflow with pip.

**Comment by aquan9** [comment]
> I'm not sure this will work if someone installs beeflow with pip.

@pagrubel Does a pip install change the BEE directory structure somehow? Which part of the code are you concerned with?

**Comment by pagrubel** [comment]
I don't know if the files are actually available when we do a pip install.

**Comment by pagrubel** [comment]
I guess it may be time to publish again and try it out

**Review by pagrubel — APPROVED** [review]
Okay you can ignore my previous comments I think it will work with pip.

**Pull request merged**
