### PR TITLE
CWL compliant builder methods

### LINKED ISSUE #217: build: Implement build class def as written in README.md
Creating an issue to track progress on the first pass at a build component class definition.

This issue will track the progress toward a concrete implementation of the `beeflow/common/build/README.md` on the develop branch.

This issue will be closed when basic functionality is achieved. Further development will occur when new issues are created to add or change functionality.

### LINKED ISSUE #234: build: dockerPull
Moving discussion from #219 regarding dockerPull here.

### LINKED ISSUE #245: build: dockerImport
According to the CWL spec, the function of dockerImport should be:

> Provide HTTP URL to download and gunzip a Docker images using `docker import.`

I will implement in Charliecloud first, using ch-tar2dir to unpack a tarball into a directory. By default, this directory will be /var/tmp/.

Pseudo-code for this feature will be:
```
try:
    tar2dir pathtofile /var/tmp/
except FileNotFoundError:
    wget path output_dir
    tar2dir output_dir/pathrofile /var/tmp/
```

### LINKED ISSUE #246: build: dockerLoad (Charliecloud)
I'd like to start a discussion about CWL dockerLoad spec for Charliecloud.

The `docker load` command refers to gunzip'ing a Docker image, complete with image layers and metadata. Since Charliecloud does not have the image layering concept, this command is not directly replicated with Charliecloud. Should we:

1. Throw an error and exit the builder with fail status.
2. Treat dockerLoad as a wrapper for `dockerImport`*
3. Something else?

@trandles-lanl @pagrubel 

*`docker import` refers to the process of gunzip'ing a flattened container image to a pre-defined directory, which differs from `docker load` because the tarball does not container image layer metadata.

### LINKED ISSUE #247: build: dockerOutputDirectory
Set the designated output directory to a specific location inside the Docker container.

This will be treated as a setter to the builder object. This should take a BeeConfig argument.

### PR DESCRIPTION
**Pull request by qwofford**
I outlined the structure of our build system, using print statements to demonstrate that the structure is valid. This PR is pylama compliant. This PR is a long-term WIP.

```
>>> from beeflow.common.build.build_interface import BuildInterface
>>> a = BuildInterface()
BuildInterface init: <beeflow.common.build.build_interface.BuildInterface object at 0x2ba481ddf090> <class 'beeflow.common.build.container_drivers.CharliecloudBuildDriver'>
>>> from beeflow.common.build.container_drivers import CharliecloudBuildDriver, SingularityBuildDriver
>>> a = CharliecloudBuildDriver()
>>> a.
a.build(                  a.initialize_builder(     a.parse_build_config(     a.validate_build(         a.validate_build_config(
>>> a.initialize_builder(requirements='yadda',hints='blah',bc_options={})
Charliecloud, initialize_builder: <beeflow.common.build.container_drivers.CharliecloudBuildDriver object at 0x2ba481ddf050> yadda blah {} .
>>> a = SingularityBuildDriver()
>>> a.initialize_builder(requirements='yadda',hints='blah',bc_options={})
Singularity, initialize_builder: <beeflow.common.build.container_drivers.SingularityBuildDriver object at 0x2ba481ddd610> yadda blah {} .
>>> 
```

Will update #217 as these dummy print methods take on practical use.

### CODE REVIEW

**Review by rstyd — APPROVED** [review]

**Review by pagrubel — APPROVED** [review]
This looks great!

**Review by pagrubel — APPROVED** [review]
As stated in the previous comment I approve this PR.

**Review by trandles-lanl — COMMENTED** [review]
After much, very good, discussion today I approve.

**Review by rstyd — APPROVED** [review]
Ninja approval

**Pull request merged**
