### PR TITLE
Update documentation for the integration tests

### PR DESCRIPTION
**Pull request by jtronge**
I think this should address issue #859, at least for the integration tests. I've added some more info about what tests are actually being run, how to show those, and how to run tests not on by default.

### CODE REVIEW

**Review by pagrubel — COMMENTED** [review]
@jtronge This looks good. I don't know why but when I build it the reference to the command line interface doesn't work correctly, but it doesn't work correctly for me on develop branch either.

**Review by pagrubel — CHANGES_REQUESTED** [review]
I found the reference problem, there needs to be two dots in commands.rst at the beginning of line 1 not one dot.

**Review by rstyd — APPROVED** [review]
Looks good to me!

**Review by rstyd — APPROVED** [review]
This addresses the requested changes.

**Review by pagrubel — APPROVED** [review]

**Pull request merged**
